some clear

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,13 +1,13 @@
 name: Tests and deploy
 # https://stackoverflow.com/questions/8466223/reuse-a-block-of-code-in-yaml
+#        echo "$DOCKER_CONTAINER_NAME_FULL" > debug.txt && scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r -i $HOME/.ssh/key debug.txt $SERVER_SSH_USER@$SERVER_ADDRES:/home/$SERVER_SSH_USER/dockers/iso
+
 on: [push]
 #on:
 #  pull_request:
 #  push:
 #    branches:
 #      - master
-
-
 
 env:
   SERVER_SSH_USER: ${{ secrets.SERVER_SSH_USER }}
@@ -62,22 +62,10 @@ jobs:
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker build -t $DOCKER_CONTAINER_NAME_FULL .
         docker push $DOCKER_CONTAINER_NAME_FULL
-#        echo "$DOCKER_CONTAINER_NAME_FULL" > debug.txt && scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r -i $HOME/.ssh/key debug.txt $SERVER_SSH_USER@$SERVER_ADDRES:/home/$SERVER_SSH_USER/dockers/iso
 
-    - name: Configure SSH priv key
-      #if: github.ref == 'refs/heads/master' && job.status == 'success'
-      run: |
-        SSH_PRIVATE_KEY="$SERVER_SSH_PRIV_KEY"
-        SSH_KNOWN_HOSTS="$SERVER_ADDRES"
-        test -n "$SSH_PRIVATE_KEY" || ( echo "missing variable SSH_PRIVATE_KEY" && exit 1)
-        test -n "$SSH_KNOWN_HOSTS" || ( echo "missing variable SSH_KNOWN_HOSTS" && exit 1)
-        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
-        eval $(ssh-agent -s)
-        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
-        mkdir -p ~/.ssh
-        chmod 700 ~/.ssh
-        ssh-keyscan -H "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
-        chmod 644 ~/.ssh/known_hosts
+#    - name: Configure SSH priv key
+#      if: github.ref == 'refs/heads/master' && job.status == 'success'
+#      run: |
 #        set -eu
 #        mkdir "$HOME/.ssh"
 #        echo "$SERVER_SSH_PRIV_KEY" > "$HOME/.ssh/key"
@@ -89,6 +77,18 @@ jobs:
         GIT_BRANCH=$(git branch --show-current)
         GIT_HASH=$(git log -1 --pretty=format:%h)
         export DOCKER_CONTAINER_NAME_FULL="${DOCKER_USER}/${DOCKER_CONTAINER_NAME}-${GIT_BRANCH}:${GIT_HASH}"
+        
+        SSH_PRIVATE_KEY="$SERVER_SSH_PRIV_KEY"
+        SSH_KNOWN_HOSTS="$SERVER_ADDRES"
+        test -n "$SSH_PRIVATE_KEY" || ( echo "missing variable SSH_PRIVATE_KEY" && exit 1)
+        test -n "$SSH_KNOWN_HOSTS" || ( echo "missing variable SSH_KNOWN_HOSTS" && exit 1)
+        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
+        eval $(ssh-agent -s)
+        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
+        mkdir -p ~/.ssh
+        chmod 700 ~/.ssh
+        ssh-keyscan -H "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
+        chmod 644 ~/.ssh/known_hosts
         
         docker-compose -H "ssh://$SERVER_SSH_USER@$SERVER_ADDRES" pull
         docker-compose -H "ssh://$SERVER_SSH_USER@$SERVER_ADDRES" up -d
