a5

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -70,9 +70,21 @@ jobs:
         export DOCKER_CONTAINER_NAME_FULL="${DOCKER_USER}/${DOCKER_CONTAINER_NAME}-${GIT_BRANCH}:${GIT_HASH}"
 
 
-        SCRIPT=.github/workflows/init-ssh.sh
-        chmod +x $SCRIPT
-        sh $SCRIPT "$SERVER_SSH_PRIV_KEY" "$SERVER_ADDRES"
+#        SCRIPT=.github/workflows/init-ssh.sh
+#        chmod +x $SCRIPT
+#        sh $SCRIPT "$SERVER_SSH_PRIV_KEY" "$SERVER_ADDRES"
+
+        SSH_PRIVATE_KEY="$SERVER_SSH_PRIV_KEY"
+        SSH_KNOWN_HOSTS="$SERVER_ADDRES"
+        test -n "$SSH_PRIVATE_KEY" || ( echo "missing variable SSH_PRIVATE_KEY" && exit 1)
+        test -n "$SSH_KNOWN_HOSTS" || ( echo "missing variable SSH_KNOWN_HOSTS" && exit 1)
+        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
+        eval $(ssh-agent -s)
+        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
+        mkdir -p ~/.ssh
+        chmod 700 ~/.ssh
+        ssh-keyscan -H "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
+        chmod 644 ~/.ssh/known_hosts
 
         DEBUG=$DOCKER_CONTAINER_NAME_FULL
         DEBUG="$DEBUG $(git branch -a)"
