ok?7

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,34 +24,34 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - name: Fail on fork
-      if: github.repository_owner != 'koshi8bit'
-      run: |
-        echo "Pipe works only on koshi8bit repo"
-        exit 1
-    - uses: actions/checkout@v2
-    - run: |
-        git fetch --prune --unshallow
-
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v1
-      with:
-        python-version: 3.10.4
-
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-
-    - name: Lint flake8
-      uses: py-actions/flake8@v2
-      with:
-        max-line-length: "120"
-        path: "src"
-
-    - name: Test with pytest
-      run: |
-        python -m unittest tests/test_app.py
+#    - name: Fail on fork
+#      if: github.repository_owner != 'koshi8bit'
+#      run: |
+#        echo "Pipe works only on koshi8bit repo"
+#        exit 1
+#    - uses: actions/checkout@v2
+#    - run: |
+#        git fetch --prune --unshallow
+#
+#    - name: Set up Python 3.10
+#      uses: actions/setup-python@v1
+#      with:
+#        python-version: 3.10.4
+#
+#    - name: Install dependencies
+#      run: |
+#        python -m pip install --upgrade pip
+#        pip install -r requirements.txt
+#
+#    - name: Lint flake8
+#      uses: py-actions/flake8@v2
+#      with:
+#        max-line-length: "120"
+#        path: "src"
+#
+#    - name: Test with pytest
+#      run: |
+#        python -m unittest tests/test_app.py
 
     - name: Configure SSH priv key
       #if: github.ref == 'refs/heads/master' && job.status == 'success'
@@ -65,7 +65,7 @@ jobs:
       #if: github.ref == 'refs/heads/master' && job.status == 'success'
       run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
-        echo "$DOCKER_CONTAINER_NAME_FULL" > debug.txt && scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r -i $HOME/.ssh/key debug.txt $SERVER_SSH_USER@$SERVER_ADDRES:/home/$SERVER_SSH_USER/dockers/iso
+        echo "$GIT_BRANCH" > debug.txt && scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r -i $HOME/.ssh/key debug.txt $SERVER_SSH_USER@$SERVER_ADDRES:/home/$SERVER_SSH_USER/dockers/iso
         docker build -t $DOCKER_CONTAINER_NAME_FULL .
         docker push $DOCKER_CONTAINER_NAME_FULL
 
