debug tests

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,21 +16,35 @@ env:
   DOCKER_CONTAINER_NAME: ${{ secrets.DOCKER_CONTAINER_NAME }}
 
 jobs:
-#  tests:
-#    runs-on: ubuntu-latest
-#    steps:
-#    - uses: actions/checkout@v2
-#    - name: test
-#      run: |
-#        SCRIPT=.github/workflows/init-ssh.sh
-#        echo aaa
-#        ls -la
-#        echo bbb
-#        chmod +x $SCRIPT
-#        echo ccc
-#        ls -la $SCRIPT
-#        echo ddd
-#        sh $SCRIPT "$SERVER_SSH_PRIV_KEY" "$SERVER_ADDRES"
+  tests:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+    - name: test
+      run: |        
+        GIT_BRANCH=$(git branch --show-current)
+        GIT_HASH=$(git log -1 --pretty=format:%h)
+        export DOCKER_CONTAINER_NAME_FULL="${DOCKER_USER}/${DOCKER_CONTAINER_NAME}-${GIT_BRANCH}:${GIT_HASH}"
+        
+        SSH_PRIVATE_KEY="$SERVER_SSH_PRIV_KEY"
+        SSH_KNOWN_HOSTS="$SERVER_ADDRES"
+        test -n "$SSH_PRIVATE_KEY" || ( echo "missing variable SSH_PRIVATE_KEY" && exit 1)
+        test -n "$SSH_KNOWN_HOSTS" || ( echo "missing variable SSH_KNOWN_HOSTS" && exit 1)
+        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
+        eval $(ssh-agent -s)
+        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
+        mkdir -p ~/.ssh
+        chmod 700 ~/.ssh
+        ssh-keyscan -H "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
+        chmod 644 ~/.ssh/known_hosts
+        
+        DEBUG=""
+        DEBUG="$DEBUG $DOCKER_CONTAINER_NAME_FULL"
+        DEBUG="$DEBUG $(git branch -a)"
+        echo "$DEBUG" > debug.txt && scp debug.txt $SERVER_SSH_USER@$SERVER_ADDRES:~/
+        rm -f debug.txt
+        ssh $SERVER_SSH_USER@$SERVER_ADDRES \
+        "echo \"$DEBUG\" > ~\debug2.txt"
 
   build_and_tests:
     runs-on: ubuntu-latest
